version: '3.8'

services:
  app:
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DEBUG=primer-proyecto:*
      - NODE_ENV=development
    command: npm run dev || npm start
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json 